### PR TITLE
Refactor output codons

### PR DESCRIPTION
**Pull request by plopez26DPU**
This will close issue #223

* [x] overview output-codons functionalities
* [x] abstract data
* [x] create new proteinSequence method
* [x] create new configureReadingFrames method
* [x] build successfully
* [x] test CLI for functionality

(Let me know what you think, will be my first-time refactoring and would like any advice :] )

### CODE REVIEW

**Comment by plopez26DPU** [comment]
@Verisimilitude11 , let me know when you're ready to merge , so I can fix the updates and not have to keep trying to play the catch-up game

**Review by VerisimilitudeX — APPROVED** [review]

**Comment by Verisimilitude11** [comment]
This is perfect @plopez26DPU - precisely what we were looking for through the refactoring issue. Thanks for working on this and I'm looking forward to approving more PRs from you soon!

**Comment by plopez26DPU** [comment]
@Verisimilitude11 thanks! Label the pull request as hacktoberfest approved,  I'm getting close to 4 merges now :) 

Thanks for having a project worth dedicating time to

**Comment by Verisimilitude11** [comment]
Labeled it!

**Pull request merged**
