### PR TITLE
Adds parallelized method buildCodonMap

### PR DESCRIPTION
**Pull request by garyglatfelter**
Improves buildCodonMap. Adds parallelized method; Selects between the non-parallelized or parallelezed methods based on DNA string length. Resolves Verisimilitude11/DNAnalyzer#261

### CODE REVIEW

**Comment by garyglatfelter** [comment]
The arguments for the Junit tests are in the right order, however, it still states there is a style error.

**Comment by Verisimilitude11** [comment]
> The arguments for the Junit tests are in the right order, however, it still states there is a style error.

@garyglatfelter Don't worry about that - AI isn't always correct. I'll take a look at your PR tomorrow and merge it. Let's discuss on next steps in the Discord server. Again, thank you so much for contributing, I really appreciate it!

**Comment by Verisimilitude11** [comment]
@LimesKey can you verify this PR? It looks good to me but I want to get a second set of eyes since this is a relatively large change.

**Review by Verisimilitude11 — APPROVED** [review]
Looks good to me! I'm surprised to see how much faster the program got because of the parallelized version, amazing job! Are there any other places where we can do the same?

**Review by LimesKey — CHANGES_REQUESTED** [review]
Is there anyway you can make the test file almost universal, as in, in this code it can pull any line from that file instead having to pull that exact line? This is the issue I'm having with my PR #339. Other than that it looks good!

```
        String brcaDnaString = readFile(brcaPath.toFile());
        //a = 3790, t = 2837, g = 1903, c = 1804
        long[] expected = {3790, 2837, 1903, 1804};
        long[] actual = DNAAnalysis.countBasePairs(brcaDnaString);
        assertArrayEquals(expected, actual);
```

**Comment by VerisimilitudeX** [comment]
@LimesKey it looks like we may need to hire an expert git merger! I have absolutely no clue on how I would merge this. But the code on its own works fine - @garyglatfelter is great at making code efficient (thanks!).

**Comment by VerisimilitudeX** [comment]
@garyglatfelter could you please help us fix the git merge conflicts? Thanks! I'd love to merge your PR as soon as possible!

**Comment by garyglatfelter** [comment]
@VerisimilitudeX  Sure, I'll try to look into it tomorrow

**Comment by VerisimilitudeX** [comment]
Great, thank you so much!

________________________________

**Comment by VerisimilitudeX** [comment]
@garyglatfelter did you get it fixed? Sorry if I'm disturbing you but I really appreciate the contributions you have made to this project!

**Pull request closed without merging**
