### PR TITLE
About page and nav bar

### PR DESCRIPTION
**Pull request by krishnabiradar310802**
Signed-off-by: krishnabiradar310802 <114948459+krishnabiradar310802@users.noreply.github.com>

### CODE REVIEW

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
About page link in navbar isn't working

**Review by LimesKey — CHANGES_REQUESTED** [review]
I'm not a huge fan of the navbar changing positions depending on which one you click on, it makes it distracting to navigate. 
image


Can you store the images locally instead of using a external site to do that; `background-image: url(https://i.postimg.cc/857jHw2q/Screenshot-2020-04-16-at-1-07-06-PM.png);`, just in case the site gets taken down or something.

The logo for DNAnalyzer is stretched and is not of the same background colour as the navbar, it looks slightly lighter.
image

**Comment by Verisimilitude11** [comment]
Thanks for the feedback @LimesKey! I gave the same feedback to him as well via LinkedIn DMs.

**Comment by Verisimilitude11** [comment]
@krishnabiradar310802 how far are you on fixing this PR?

**Comment by krishnabiradar310802** [comment]
Will complete in few days

**Pull request closed without merging**
