### PR TITLE
Binary FASTA (.fab) file format

### LINKED ISSUE #215: Store .fa DNA files in Smaller File Size
Use a more efficient file format as the DNA FASTA files right now are very big and take a lot of time to download while cloning the DNAnalyzer repository.

### PR DESCRIPTION
**Pull request by ImpossibleReality**
Fully closes #215

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
@ImpossibleReality let me know when you want me to review

**Comment by LimesKey** [comment]
Can you try to measure how long it takes to encode/decode a 1GB .fasta file? Also, to confirm the program has to also decode the binary .fab file for analysis from the program?

**Comment by LimesKey** [comment]
After talking more with @ImpossibleReality, we mostly decided to incorporate Deflate compression as it was the best choice out of the options below. It seems to be much faster than expected so the program will be uncompressing and decoding the .FAB file on the fly. ImpossibleReality might also create a .FABC file format to separate the compressed and non-compressed binary versions.

Below are some results by me,
**Source File: FASTA RANDOM BINARY - 50MB**
**Deflate** Compression -  3 Seconds - _27.2MB_
**Deflate64** Compression - 5 Seconds - _27.2MB_
**LZMA2** Compression - 32 Seconds - _25.7_
**PPMD** Compression - 6 Seconds - _25.2MB_

I have a few questions still,
- Is this able to be ran as multi-threaded?
- Can you clarify of what you meant by the difficulty of compressing NULL characters?
- Is it possible for this to be ran with the program without having to decode binary for the analysis? Although the performance is pretty impressive, future-proofing this and trying to squeeze out performance will make a significant impact in the long run.
- Will you be coding more of this in Rust or staying with Java?

**Comment by LimesKey** [comment]
@Verisimilitude11 is ImpossibleReality still working on this?

**Comment by Verisimilitude11** [comment]
> @Verisimilitude11 is ImpossibleReality still working on this?

No...

**Comment by Verisimilitude11** [comment]
Although I think he did get started on the basics of the file format, I'll need to check on where he left off. Then we can create a new issue for it that will give contributors details on what to add.

**Comment by Verisimilitude11** [comment]
@ImpossibleReality could you (briefly) tell us where you left off on if you remember? Thanks for contributing btw!

**Comment by LimesKey** [comment]
Hi, if anyone is interested in running this part of the program to test it. I have discovered the command to run to compress the files.

Run this in PowerShell as Administrator and make sure your in the correct directory for the DNAnalyzer jar file,
```powershell
$user_path = $env:USERPROFILE
java -jar build/libs/DNAnalyzer.jar compress "$user_path\Documents\GitHub\DNAnalyzer\assets\dna\random\dnalong.fa" "$user_path\Documents\GitHub\DNAnalyzer\assets\dna\random\dnalong_compressed.fa"
```
Replace the DNA file location path with where you stored the file.

**Comment by Verisimilitude11** [comment]
Hmm this is interesting. It worked! Can you also put this in #development for reference? Thanks!

**Comment by VerisimilitudeX** [comment]
@LimesKey I'm going to take a look at this - let me know if you have any ideas.

**Pull request closed without merging**
