### PR TITLE
Intro spring boot

### PR DESCRIPTION
**Pull request by MartinGallauner**
Hi!

Regarding [this issue.](https://github.com/VerisimilitudeX/DNAnalyzer/issues/426)
In this pull request, I introduced many changes, and I'm sure there will be a lot of feedback.

My primary goal was to don't break any existing functionality. The secondary goal was to introduce Spring Boot and a first simple controller class offering two endpoints concerned with getting/setting the openai api-key.
Maybe we want to stick to the current solution for security reasons, though.

**This is what I did:**
- Introduced Spring Boot 3.1.4
- Added a new class named `DNAnalyzerApplication` with another main method.  I did that so anyone can consciously run the application either in the current (cli/gui) version or in the future webservice version.
- I applied a clean architecture design pattern to place the new controller, service, request, and response classes. Please let me know what you think about that.
- Added lombok library. I wouldn't mind removing that again.
- Added springdocs, which is creating a swagger-ui page for us. When the application is running, you can reach it by navigating [here](http://localhost:8080/swagger-ui/index.html).

**What's missing?**
A lot.
1. The whole analysis functionality needs to be available by REST. To do that, we must first separate the big `DNAAnalysis` record by domain and presentation logic. 
If we stick to clean architecture, I would implement something like a SystemOutAdapter and keep the domain logic within a service class.
2. Documentation. I didn't document any work in progress since users shouldn't use that yet.

### CODE REVIEW

**Comment by VerisimilitudeX** [comment]
Everything works perfectly! This gives me a good starting point to work off of. Could you please fix the merge conflicts real quick so that I can merge it? Thanks!

**Review by VerisimilitudeX — APPROVED** [review]
Looks good to me

**Comment by MartinGallauner** [comment]
@VerisimilitudeX 
I resolved the merge conflict and all findings in the build pipeline by now.
There is only one false positive left because I wrote a test using a mock key.
Can you tell me how to skip that and merge?

**Comment by VerisimilitudeX** [comment]
Well, most secret scanning workflow support a "suppress warning" feature, although GitGuardian doesn't unfortunately. For example:
@SuppressWarnings("squid:S1234") // this is to ignore SonarQube's rule, replace "S1234"
public class MyClass {
    ...
}

I think I can go ahead and merge this and add this test file to the list of GitGuardian's exclusion list later. Thanks for the PR btw!

@MartinGallauner one last thing - could you please add some documentation under docs/* that tells devs how to run the features that you just added in this PR? I would really appreciate that. Thanks!

**Comment by MartinGallauner** [comment]
@VerisimilitudeX 
Sure thing! I will add the docs to the next iteration when there is some actual functionality.

**Pull request merged**
