### PR TITLE
Wrong thread for swing method invocation

### LINKED ISSUE #343: (JAVA-W1062) Wrong thread for swing method invocation
## Description
Methods `show()`, `setVisible()`, and `pack()` must not be invoked on the main thread.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1062/occurrences/](https://deepsource.io/gh/Verisimilitude11/DNAnalyzer/issue/JAVA-W1062/occurrences/)

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR fixes the following issue:
fixes #343 

## Changes made:
- Different methods are invoked on the event dispatch thread.

### CODE REVIEW

**Comment by Verisimilitude11** [comment]
@Rishav1707 I get the following error when running the code:
image
Please test your code before opening a PR. Also, could you please star our repository to show your support? Thanks!

**Comment by Verisimilitude11** [comment]
image
@Rishav1707 please fix this bug. Thank you!

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
image

@Rishav1707 please fix this bug. Thank you!

**Review by Verisimilitude11 — CHANGES_REQUESTED** [review]
@Rishav1707 have you tested your code by actually running it? There are still a lot of bugs in your code.

**Comment by VerisimilitudeX** [comment]
@Rishav1707 please fix.

**Pull request closed without merging**
